<?php

/*
 +-----------------------------------------------------------------------+
 | localization/az_AZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Orkhan Guliyev <proger@box.az>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Yığılmış ünvanlar';
$labels['useautoabook'] = 'Yığılmış ünvanları istifadə et';
$labels['useforcompletion'] = 'Yığılmış ünvanları avtobitmə üçün istifadə et';
$labels['contactremoved'] = 'Kontak (lar) yığımdan ünvan kitabçasını sildi';
$labels['contactmoved'] = 'Kontakt (lar) yığımdan köçdü';

?>
