<?php
$labels = array();
$labels['automaticallycollected']  = 'Събрани адреси';
$labels['useautoabook']  = 'Използване на автоматична адресна книга';
$labels['useforcompletion'] = 'Използване на автоматично събраните адреси за автоматично довършване';
$labels['contactremoved'] = 'Контакти изтрити от автоматичната адресна книга';
$labels['contactmoved'] = 'Контакти преместени от автоматичната адресна книга';
?>
