<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bg_BG/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Автоматично събирана';
$labels['useautoabook'] = 'Използване на автоматична адресна книга';
$labels['useforcompletion'] = 'Използване на автоматично събраните адреси за автоматично довършване';
$labels['contactremoved'] = 'Контакт (а) заличава от автоматичното адресната книга';
$labels['contactmoved'] = 'Контакт (а) преместени от автоматична адресната книга';

?>
