<?php

/*
 +-----------------------------------------------------------------------+
 | localization/br/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Denis                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Dastumet emgefreek';
$labels['useautoabook'] = 'Arverañ ar c\'harned chomlec\'hioù emgefreek';
$labels['contactremoved'] = 'Darempred(où) dilamet diouzh ar c\'harned chomlec\'hioù emgefreek';
$labels['contactmoved'] = 'Darempred(où) dilec\'hiet diouzh ar c\'harned chomlec\'hioù emgefreek';

?>
