<?php

/*
 +-----------------------------------------------------------------------+
 | localization/bs_BA/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenan Dervišević <kenan3008@gmail.com>                      |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automatski prikupljeno';
$labels['useautoabook'] = 'Koristi automatski adresar';
$labels['useforcompletion'] = 'Koristi automatski prikupljene adrese za samopopunjavanje';
$labels['contactremoved'] = 'Kontakti su obrisani iz automatskog adresara';
$labels['contactmoved'] = 'Kontakti su premješteni iz automatskog adresara';

?>
