<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ca_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jordi Sanfeliu <jordi@fibranet.cat>                           |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Recollida automàticament';
$labels['useautoabook'] = 'Fes servir la llibreta d\'adreces automàtica';
$labels['useforcompletion'] = 'Fes servir les adreces recollides automàticament per l\'autocompleció';
$labels['contactremoved'] = 'Contacte(s) suprimit(s) de la llibreta d\'adreces automàtica';
$labels['contactmoved'] = 'Contacte(s) mogut(s) des de la llibreta d\'adreces automàtica';

?>
