<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cs_CZ/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Tomáš Kyzlink                                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automaticky shromážděné';
$labels['useautoabook'] = 'Použít automatický adresář';
$labels['useforcompletion'] = 'Použít automaticky shromážděné adresy pro automatické dokončování';
$labels['contactremoved'] = 'Kontakty z automatického adresáře byly smazány';
$labels['contactmoved'] = 'Kontakty z automatického adresáře byly přesunuty';

?>
