<?php

/*
 +-----------------------------------------------------------------------+
 | localization/cy_GB/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Dafydd Tomos                                                  |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Casglwyd yn Awtomatig';
$labels['useautoabook'] = 'Defnyddio llyfr cyfeiriad awtomatig';
$labels['useforcompletion'] = 'Defnyddio cyfeiriadau casglwyd yn awtomatig ar gyfer awtogwblhau';
$labels['contactremoved'] = 'Dilewyd cysylltiad o\'r llyfr cyfeiriadau awtomatig';
$labels['contactmoved'] = 'Symudwyd cyswllt o\'r llyfr cyfeiriadau awtomatig';

?>
