<?php

/*
 +-----------------------------------------------------------------------+
 | localization/de_DE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Gesammelte Adressen';
$labels['useautoabook'] = 'Gesammelte Adressen verwenden';
$labels['useforcompletion'] = 'Gesammelte Adressen zur Autovervollständigung verwenden';
$labels['contactremoved'] = 'Kontakt(e) von gesammelten Adressen entfernt';
$labels['contactmoved'] = 'Kontakt(e) von gesammelten Adressen verschoben';

?>
