<?php
$labels = array();
$labels['automaticallycollected']  = 'Αυτομάτως Συλλεγμένες';
$labels['useautoabook']  = 'Αυτόματη καταχώρηση παραληπτών στις επαφές';
$labels['useforcompletion'] = 'Χρήση συλλέγονται αυτόματα διευθύνσεις για αυτόματη συμπλήρωση';
$labels['contactremoved'] = 'Επικοινωνία (α) διαγράφονται αυτόματα από το βιβλίο διευθύνσεων';
$labels['contactmoved'] = 'Η επαφή μεταφέρθηκε στις προσωπικές επαφές';
?>
