<?php

/*
 +-----------------------------------------------------------------------+
 | localization/el_GR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Αυτομάτως Συλλεγμένες';
$labels['useautoabook'] = 'Αυτόματη καταχώρηση παραληπτών στις επαφές';
$labels['useforcompletion'] = 'Χρήση συλλέγονται αυτόματα διευθύνσεις για αυτόματη συμπλήρωση';
$labels['contactremoved'] = 'Επικοινωνία (α) διαγράφονται αυτόματα από το βιβλίο διευθύνσεων';
$labels['contactmoved'] = 'Η επαφή μεταφέρθηκε στις προσωπικές επαφές';

?>
