<?php
$labels = array();
$labels['automaticallycollected']  = 'Автоматично събрани адреси';
$labels['useautoabook']  = 'Използвай aвтоматично събраните адреси';
$labels['useforcompletion'] = 'При въвеждане на получател, предлагай автоматично сънраните адреси';
$labels['contactremoved'] = 'Контакти, изтрити от автоматичната адресна книга';
$labels['contactmoved'] = 'Контакти, преместени от автоматичната адресна книга';
?>
