<?php
/*
+-----------------------------------------------------------------------+
| Translator:   Davide Garabana. Updated by gatitac                     | 
+-----------------------------------------------------------------------+

*/
$labels = array();
$labels['automaticallycollected']  = 'Direcciones recientes';
$labels['useautoabook']  = 'Guardar automáticamente las direcciones a las que se envía correo';
$labels['useforcompletion'] = 'Usar las direcciones automáticamente recogidas para la autocompleción';
$labels['contactremoved'] = 'Contacto(s) suprimidos de la libreta de direcciones automática';
$labels['contactmoved'] = 'El contacto se ha añadido a la libreta de direcciones';
?>
