<?php
/*
+-----------------------------------------------------------------------+
| Translator:   Davide Garabana. Updated by gatitac                     | 
+-----------------------------------------------------------------------+

*/
$labels = array();
$labels['automaticallycollected']  = 'Automáticamente recuperada';
$labels['useautoabook']  = 'Usar la libreta de direcciones automática';
$labels['useforcompletion'] = 'Usar las direcciones automáticamente recuperadas para la autocompletación';
$labels['contactremoved'] = 'Contacto(s) suprimido(s) de la libreta de direcciones automática';
$labels['contactmoved'] = 'Contacto(s) trasladado(s) desde la libreta de direcciones automática';
?>
