<?php
/*
+-----------------------------------------------------------------------+
| Translator:   Davide Garabana                                         |
+-----------------------------------------------------------------------+

*/
$labels = array();
$labels['automaticallycollected']  = 'Direcciones recientes';
$labels['useautoabook']  = 'Guardar automáticamente las direcciones a las que se envía correo';

$messages = array();
$messages['contactmoved'] = 'El contacto se ha añadido a la libreta de direcciones';
?>