<?php

/*
 +-----------------------------------------------------------------------+
 | localization/et_EE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: yllar                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automaatselt kogutud';
$labels['useautoabook'] = 'Kasuta automaatset aadressiraamatut';
$labels['useforcompletion'] = 'Kasuta automaatselt kogutud kontakte automaatlõpetuses';
$labels['contactremoved'] = 'Kontakt(id) automaatsest aadressiraamatust kustutatud';
$labels['contactmoved'] = 'Kontakt(id) automaatsest aadressiraamatust eemaldatud';

?>
