<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fa_IR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Hamid <abbaszadeh.h@gmail.com>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'به صورت خودکار جمع‌آوری شد';
$labels['useautoabook'] = 'استفاده از دفترچه آدرس خودکار';
$labels['useforcompletion'] = 'استفاده از آدرس‌های خودکار جمع‌آوری شده برای تکمیل کردن خودکار';
$labels['contactremoved'] = 'تماس(ها) از دفترچه آدرس خودکار حذف شد(ند).';
$labels['contactmoved'] = 'تماس(ها) از دفترچه آدرس خودکار منتقل شد(ند).';

?>
