<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fi_FI/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jiri Grönroos                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automaattisesti kerätty';
$labels['useautoabook'] = 'Käytä automaattista osoitekirjaa';
$labels['useforcompletion'] = 'Käytä automaattisesti kerättyjä osoitteita automaattitäydennystä varten';
$labels['contactremoved'] = 'Automaattisesta osoitekirjasta poistetut osoitteet';
$labels['contactmoved'] = 'Automaattisesta osoitekirjasta siirretyt osoitteet';

?>
