<?php
$labels = array();
$labels['automaticallycollected']  = 'Enderezos recentes';
$labels['useautoabook']  = 'Gardar automáticamente os enderezos aos que se envía correo';
$labels['useforcompletion'] = 'Use automatically collected addresses for autocompletion';
$labels['contactremoved'] = 'Contact(s) deleted from automatic address book';
$labels['contactmoved'] = 'Engadiuse o contacto ao caderno de enderezos';
?>
