<?php

/*
 +-----------------------------------------------------------------------+
 | localization/gl_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Enderezos recentes';
$labels['useautoabook'] = 'Gardar automáticamente os enderezos aos que se envía correo';
$labels['contactmoved'] = 'Engadiuse o contacto ao caderno de enderezos';

?>
