<?php
/*
+-----------------------------------------------------------------------+
| Translator:   Davide Garabana                                         |
+-----------------------------------------------------------------------+

*/
$labels = array();
$labels['automaticallycollected']  = 'Enderezos recentes';
$labels['useautoabook']  = 'Gardar automáticamente os enderezos aos que se envía correo';

$messages = array();
$messages['contactmoved'] = 'Engadiuse o contacto ao caderno de enderezos';
?>