<?php

/*
 +-----------------------------------------------------------------------+
 | localization/he_IL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Moshe Leibovitch <moish@mln.co.il>                            |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'נאסף אוטומטית';
$labels['useautoabook'] = 'שימוש באיסוף אוטומטי של כתובות';
$labels['useforcompletion'] = 'האם להציע כתובות שנאספו אוטומטית';
$labels['contactremoved'] = 'איש הקשר נמחק מרשימת הכתובות שנאספו אוטומטית';
$labels['contactmoved'] = 'איש הקשר הועבר מרשימת הכתובות שנאספו אוטומטית';

?>
