<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatikusan begy&#369;jt&#246;tt';
$labels['useautoabook']  = 'C&#237;mjegyz&#233;k automatikus t&#246;lt&#233;se';
$labels['useforcompletion'] = 'használata automatikusan gyűjtött címek automatikus kiegészítése';
$labels['contactremoved'] = 'Contact (ek) el kell hagyni az automatikus címjegyzék';
$labels['contactmoved'] = 'Kapcsolat (ok) áthelyezve az automatikus címjegyzék';';
?>
