<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ja_JP/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Takahiro Kambe                                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = '自動的に収集';
$labels['useautoabook'] = '自動アドレス帳を使用';
$labels['useforcompletion'] = '自動補完に自動的に収集したアドレスを使用';
$labels['contactremoved'] = '自動アドレス帳から削除した連絡先';
$labels['contactmoved'] = '自動アドレス帳から移動した連絡先';

?>
