<?php
$labels = array();
$labels['automaticallycollected']  = 'Automatisch verzamelen contacten';
$labels['useautoabook']  = 'Verzamel geadresseerde contacten automatisch';
$labels['useforcompletion'] = 'Gebruik automatisch verzamelde contacten voor automatisch aanvullen';
$labels['contactremoved'] = 'Contact(en) verwijderd uit het automatische adresboek';
$labels['contactmoved'] = 'Contact(en) verplaatst uit het automatische adresboek';
?>
