<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nl_NL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automatisch verzameld';
$labels['useautoabook'] = 'Gebruik automatisch adresboek';
$labels['useforcompletion'] = 'Gebruik automatisch verzamelde adressen voor auto aanvullen';
$labels['contactremoved'] = 'Contacten verwijderd uit het automatische adresboek';
$labels['contactmoved'] = 'Contacten verplaatst uit het automatische adresboek';

?>
