<?php
$labels = array();
$labels['automaticallycollected'] = 'Automatisch verzameld';
$labels['useautoabook'] = 'Gebruik automatisch adresboek';
$labels['useforcompletion'] = 'Gebruik automatisch verzamelde adressen voor auto aanvullen';
$labels['contactremoved'] = 'Contacten verwijderd uit het automatische adresboek';
$labels['contactmoved'] = 'Contacten verplaatst uit het automatische adresboek';
?>
