<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_BR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Victor Benincasa <vbenincasa@gmail.com>                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Coletado automaticamente';
$labels['useautoabook'] = 'Usar catálogo de endereços automático';
$labels['useforcompletion'] = 'Usar endereços coletados automaticamente para autocompletar';
$labels['contactremoved'] = 'Contato(s) excluído(s) do catálogo de endereços automático';
$labels['contactmoved'] = 'Contato(s) movidos(s) do catálogo de endereços automático';

?>
