<?php

/*
 +-----------------------------------------------------------------------+
 | localization/pt_PT/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: David                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Recolhido automaticamente';
$labels['useautoabook'] = 'Usar o livro de endereços automático';
$labels['useforcompletion'] = 'Usar endereços recolhidos automaticamente no preenchimento automático';
$labels['contactremoved'] = 'Contacto(s) eliminado(s) do livro de endereços automático';
$labels['contactmoved'] = 'Contacto(s) movido(s) do livro de endereços automático';

?>
