<?php
$labels = array();
$labels['automaticallycollected']  = 'Собранные адреса';
$labels['useautoabook']  = 'Использовать собранные адреса';
$labels['useforcompletion'] = 'Использовать автоматически собранные адреса для автозавершения';
$labels['contactremoved'] = 'Контакт (-ы) удалил из автоматического адресную книгу';
$labels['contactmoved'] = 'Контакт (-ы) переехал из автоматического адресную книгу';
?>
