<?php

/*
 +-----------------------------------------------------------------------+
 | localization/ru_RU/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Собранные адреса';
$labels['useautoabook'] = 'Использовать собранные адреса';
$labels['useforcompletion'] = 'Использовать автоматически собранные адреса для автозавершения';
$labels['contactremoved'] = 'Контакт (-ы) удалил из автоматического адресную книгу';
$labels['contactmoved'] = 'Контакт (-ы) переехал из автоматического адресную книгу';

?>
