<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sk_SK/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: panda                                                         |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automaticky zozbierané';
$labels['useautoabook'] = 'Použiť automatický adresár';
$labels['useforcompletion'] = 'Použiť automaticky zozbierané adresy pre dopĺňanie';
$labels['contactremoved'] = 'Kontakt(y) vymazané z automatického adresára';
$labels['contactmoved'] = 'Kontakt(y) presunuté z automatického adresára';

?>
