<?php

/*
 +-----------------------------------------------------------------------+
 | localization/sv_SE/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jonas Nasholm                                                 |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Automatiskt insamlad';
$labels['useautoabook'] = 'Använd automatisk adressbok';
$labels['useforcompletion'] = 'Använd automatiskt insamlade adresser vid automatisk komplettering';
$labels['contactremoved'] = 'Kontakt borttagen från automatisk adressbok';
$labels['contactmoved'] = 'Kontakt flyttad från automatisk adressbok';

?>
