<?php

/*
 +-----------------------------------------------------------------------+
 | localization/tr_TR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Orkhan Guliyev <proger@box.az>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Adreslerin yığımı';
$labels['useautoabook'] = 'Yığılmış adresleri kullan';
$labels['useforcompletion'] = 'Otodurum için yığılmış adresleri otomatik kullan';

?>
