<?php

/*
 +-----------------------------------------------------------------------+
 | localization/vi_VN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Kenny Tran <kennethanh@gmail.com>                             |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = 'Tự động thu thập';
$labels['useautoabook'] = 'Sử dụng sổ địa chỉ tự động';
$labels['useforcompletion'] = 'Sử dụng các địa chỉ thu thập tự động gõ';
$labels['contactremoved'] = 'Liên hệ đã xóa từ sổ địa chỉ tự động';
$labels['contactmoved'] = 'Liên hệ di chuyển từ sổ địa chỉ tự động';

?>
