<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_CN/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = '自动采集';
$labels['useautoabook'] = '使用自动地址簿';
$labels['useforcompletion'] = '使用自动收集地址自动完成';
$labels['contactremoved'] = '联系人从地址簿上自动删除';
$labels['contactmoved'] = '联系人从地址簿上自动移动';

?>
