<?php

/*
 +-----------------------------------------------------------------------+
 | localization/zh_TW/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: 林子忠                                                     |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['automaticallycollected'] = '自動收集';
$labels['useautoabook'] = '使用自動通訊簿';
$labels['useforcompletion'] = '使用自動收集的地址並自動完成';
$labels['contactremoved'] = '從自動通訊簿刪除聯絡人';
$labels['contactmoved'] = '從自動通訊簿移動聯絡人';

?>
